"""
Django settings for project_1 project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import datetime
from consulate import Consul
from consulate.models import agent
import socket

# Set the project root directory
# PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/kv = consul_client.kv

consul_client = Consul(host='consul')
addr = socket.gethostbyname(socket.gethostname())
kv = consul_client.kv

# Check service
checks = agent.Check(
    name='User Service Check',
    http='https://user.chat.localhost/health_check/',
    interval='10s',
    tls_skip_verify=True, #* Para que no verifique el certificado
    timeout="1s",
    status="passing"
)

# Register service
consul_client.agent.service.register(
    name='userservice',
    service_id = f'{kv["userservice/config/NAME"]}-{addr}',   #Se agrega para que tome las diferentes instancias, ver id unico.
    address=addr, #* Nombre del container de docker
    tags=[  
            "traefik.enable=true",
            "traefik.http.routers.userservice.tls=true",
            "traefik.http.services.userservice.loadbalancer.sticky.cookie=true",
            "traefik.http.middlewares.userservice-cb.circuitbreaker.expression=ResponseCodeRatio(500, 600, 0, 600) > 0.10 || NetworkErrorRatio() > 0.10 || LatencyAtQuantileMS(50.0) > 100",
            "traefik.http.routers.userservice.rule=Host(`user.chat.localhost`)",
            "traefik.http.services.userservice.loadbalancer.server.port=9000",
            "traefik.http.routers.userservice.entrypoints=http,https,mysql,redis"
        ],
    check=checks
    )

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = kv['userservice/config/SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'user.User'

# Application definition

INSTALLED_APPS = [
    'user',	
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    # 'ConsulService',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.cache.UpdateCacheMiddleware', # Para el manejo de los datos en cache
    'django.middleware.common.CommonMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware', # Para el manejo de los datos en cache
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'user_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'frontend/build'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'user_service.wsgi.application'

#! Consul configuration CON DJANGO-CONSUL (DEPRECATED)
# CONSUL_AGENT_ADDRESS = config('CONSUL_AGENT_ADDRESS')
# CONSUL_AGENT_PORT = config('CONSUL_AGENT_PORT')
# CONSUL_CHECK_URL = config('CONSUL_CHECK_URL')
# CONSUL_CHECK_INTERVAL = config('CONSUL_CHECK_INTERVAL')
# CONSUL_SERVICE_NAME = config('CONSUL_SERVICE_NAME')
# CONSUL_SERVICE_ADDRESS = config('CONSUL_SERVICE_ADDRESS')
# CONSUL_SERVICE_PORT = config('CONSUL_SERVICE_PORT')

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': kv['userservice/config/DATABASE_ENGINE'],
        'NAME': kv['userservice/config/DATABASE_NAME'],
        'USER': kv['userservice/config/DATABASE_USER'],
        'PASSWORD': kv['userservice/config/DATABASE_PASSWORD'],
        'HOST': kv['userservice/config/DATABASE_HOST'],
        'PORT': kv['userservice/config/DATABASE_PORT'],
    }
}

# Para el manejo de los datos en cache
CACHES = {
    'default': {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": kv['userservice/config/REDIS_CACHE_URL'],
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# CACHE_MIDDLEWARE_SECONDS = 300

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Configuración de SimpleJWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=1),
    #'USER_ID_CLAIM': 'user_id',
    #'USER_NAME_CLAIM': 'username',
    #"TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.MyTokenObtainPairSerializer",
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ]
}

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = kv['userservice/config/STATIC_PATH']
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'frontend/build/static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_TRUSTED_ORIGINS = ['https://*.localhost']