# Generated by Django 3.2.12 on 2023-03-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('message', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(max_length=100)),
                ('username', models.CharField(max_length=20)),
                ('group_to', models.CharField(max_length=20)),
            ],
        ),
    ]
