# Generated by Django 3.2.12 on 2023-03-27 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20230327_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='group_to',
            new_name='group_id',
        ),
    ]
