# Generated by Django 3.2.12 on 2023-03-27 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_group_to_message_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='group_id',
            new_name='group',
        ),
    ]
