@startuml Class diagram

class Users {
    - id
    - username
    - password
    - email
}

' group_to: Chat id al que se le envia el mensaje
class Messages{
    - id
    - message
    - date
    - Users_id
    - group_to
}

Users -- Messages

@enduml