@startuml Class diagram

class Users {
    - id
    - username
    - password
    - email
}

class Messages{
    - id
    - message
    - date
    - Users_id
    - group_id
}

class Group{
    - id
    - name
}

Users -- Messages
Messages -- Group

@enduml