@startuml
:User: as User
:Admin: as Admin
(Leer mensajes) as (Read)
(Escribir mensajes) as (Write)
(Crear usuarios) as (Create)
(Loguearse) as (Loguearse User)
(Loguearse) as (Loguearse Admin)

Admin --> (Loguearse Admin)
Admin --> (Loguearse User)
User --> (Loguearse User)

note right of Admin
  Encargado del manejo 
  de la base de datos.
end note

note right of User
  Enviar mensajes entre
  otros usuarios.
end note

(Loguearse Admin) <.. (Create) : <<extends>>
(Loguearse User) <.. (Read) : <<extends>>
(Loguearse User) <.. (Write) : <<extends>>

@enduml